// <auto-generated />
using System;
using CardosoResort.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CardosoResort.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CardosoResort.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Data_Atualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Data_Criacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Metros_Quadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero_Quartos")
                        .HasColumnType("int");

                    b.Property<int>("Ocupacao")
                        .HasColumnType("int");

                    b.Property<double>("Preco")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Villa com Vista Mar Lateral",
                            ImagemUrl = "https://via.placeholder.com/150",
                            Metros_Quadrados = 100,
                            Nome = "Villa Albufeira",
                            Numero_Quartos = 2,
                            Ocupacao = 10,
                            Preco = 1000.0
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Suite oceano",
                            ImagemUrl = "https://via.placeholder.com/150",
                            Metros_Quadrados = 180,
                            Nome = "Villa Deluxe",
                            Numero_Quartos = 2,
                            Ocupacao = 10,
                            Preco = 1000.0
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Villa com Vista Mar",
                            ImagemUrl = "https://via.placeholder.com/150",
                            Metros_Quadrados = 200,
                            Nome = "Villa Mar",
                            Numero_Quartos = 2,
                            Ocupacao = 10,
                            Preco = 1000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
